### Prototype build jobs ###
.build_script: &build_script
    - mkdir -p build/
    - cd build/
    - echo $CMAKE_CMD
    - $CMAKE_CMD
    - ninja

.test_script: &test_script
    - ctest -V

.build:
    variables:
        EXTRA_CMAKE_FLAGS: ""
    before_script:
        - export CMAKE_CMD="cmake -GNinja $EXTRA_CMAKE_FLAGS .."
    script:
        - *build_script

.build_and_test:
    extends: .build
    script:
        - *build_script
        - *test_script

.build_and_test_linux:
    extends: .build_and_test
    variables:
        APT_PACKAGES: "build-essential cmake ninja-build git"
        BACKPORTS_TARGET: ""
        BACKPORTS_PACKAGES: ""
    before_script:
        - |
          apt update
          apt install -y $APT_PACKAGES
          [ ! -z "$BACKPORTS_TARGET" ] && [ ! -z "$BACKPORTS_PACKAGES" ] && apt -t $BACKPORTS_TARGET install -y $BACKPORTS_PACKAGES
          export CMAKE_CMD="cmake -GNinja $EXTRA_CMAKE_FLAGS .."

### Tests ###
test:debian:buster:
    extends: .build_and_test_linux
    stage: test
    needs: []
    image: debian:buster-backports
    variables:
        APT_PACKAGES: "build-essential ninja-build git"
        BACKPORTS_TARGET: "buster-backports"
        BACKPORTS_PACKAGES: "cmake"
        EXTRA_CMAKE_FLAGS: "-DSMGL_BUILD_TESTS=ON"
    tags:
        - docker

test:debian:buster:boost:
    extends: .build_and_test_linux
    stage: test
    needs: []
    image: debian:buster-backports
    variables:
        APT_PACKAGES: "build-essential ninja-build git libboost-filesystem-dev"
        BACKPORTS_TARGET: "buster-backports"
        BACKPORTS_PACKAGES: "cmake"
        EXTRA_CMAKE_FLAGS: "-DSMGL_BUILD_TESTS=ON -DSMGL_USE_BOOSTFS=ON"
    tags:
        - docker

test:ubuntu:21.04:
    extends: .build_and_test_linux
    stage: test
    needs: []
    image: ubuntu:21.04
    variables:
        EXTRA_CMAKE_FLAGS: "-DSMGL_BUILD_TESTS=ON"
    tags:
        - docker

test:ubuntu:21.04:boost:
    extends: .build_and_test_linux
    stage: test
    needs: []
    image: ubuntu:21.04
    variables:
        APT_PACKAGES: "build-essential cmake ninja-build git libboost-filesystem-dev"
        EXTRA_CMAKE_FLAGS: "-DSMGL_BUILD_TESTS=ON -DSMGL_USE_BOOSTFS=ON"
    tags:
        - docker

### Docs ###
pages:
    stage: deploy
    needs: []
    image: debian:buster-backports
    before_script:
        - apt-get update
        - apt-get install -y build-essential doxygen graphviz texlive ghostscript
        - apt-get -t buster-backports install -y cmake
    script:
        - mkdir -p build/
        - mkdir -p public/
        - cmake -S . -B build/ -DSMGL_BUILD_DOCS=ON
        - cmake --build build/ --target docs
        - mv build/docs/html/ public/docs/
    artifacts:
        paths:
            - public
    tags:
        - docker
    only:
        - main
